export const GET_STATES = 'GET_STATES';

export const GET_TOTAL_USA_DATA = 'GET_TOTAL_USA_DATA';
export const GET_MARGINAL_DATA_USA = 'GET_MARGINAL_DATA_USA';
export const GET_TOTAL_STATES_DATA_FOR_DATE = 'GET_TOTAL_STATES_DATA_FOR_DATE';
export const GET_MARGINAL_STATES_DATA_FOR_DATE = 'GET_MARGINAL_STATES_DATA_FOR_DATE';
export const GET_TOTAL_STATE_DATA = 'GET_TOTAL_STATE_DATA';
export const GET_MARGINAL_STATE_DATA = 'GET_MARGINAL_STATE_DATA';

export const CHANGE_DATE = 'CHANGE_DATE';
export const CHANGE_STATE = 'CHANGE_STATE';
